apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-docker-kubernetes
  template:
    metadata:
      labels:
        app: spring-docker-kubernetes
    spec:
      imagePullSecrets:
        - name: container-registry
      containers:
      - name: spring-docker-kubernetes
        image: spring-docker-kubernetes:latest
        ports:
        - containerPort: 8080
