apiVersion: v1
kind: Service
metadata:
  name: spring-docker-kubernetes
spec:
  type: LoadBalancer
  selector:
      app: spring-docker-kubernetes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
